apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gradle-sample-app
  description: This is a gradle application.
  annotations:
    github.com/project-slug: backstage/backstage
    github.com/user-login: skaneria-nydig
    backstage.io/techdocs-ref: dir:.
    jira/project-key: DT
    #jira/token-type: Bearer # optional, used for Activity stream feed. If you are using Basic auth you can skip this.
spec:
  type: application
  owner: devtools-dev
  lifecycle: experimental
  system: devtools-system
