name: Cache / EFS

on:
  push

env:
  BUILDKIT_INLINE_CACHE: 1
  DOCKER_BUILDKIT: 1
  COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /home/ec2-user/efs/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: |
            sanjeev/billingmetrics-test-deploy:${{ github.sha }}
          build-args: |
            VERSION=${{ github.sha }}
          cache-from: type=local,src=/home/ec2-user/efs/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

